//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irvuewin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Irvuewin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddChannel.
        /// </summary>
        public static string Add_Channel {
            get {
                return ResourceManager.GetString("Add_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_Channel_Confirm {
            get {
                return ResourceManager.GetString("Add_Channel_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type keyword or Unsplash channel URL to search.
        /// </summary>
        public static string Add_Channel_Input_Placeholder {
            get {
                return ResourceManager.GetString("Add_Channel_Input_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsplash URLs below are supported:.
        /// </summary>
        public static string Add_Channel_Instruction {
            get {
                return ResourceManager.GetString("Add_Channel_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least 1 channel.
        /// </summary>
        public static string Add_Channel_NoneSelect_Msg {
            get {
                return ResourceManager.GetString("Add_Channel_NoneSelect_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Unsplash to find more channels:.
        /// </summary>
        public static string Add_Channel_Result_Placeholder {
            get {
                return ResourceManager.GetString("Add_Channel_Result_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Unsplash.com.
        /// </summary>
        public static string Add_Channel_Unsplash_Link {
            get {
                return ResourceManager.GetString("Add_Channel_Unsplash_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete reserved channel.
        /// </summary>
        public static string Channel_Reserved_Channel {
            get {
                return ResourceManager.GetString("Channel_Reserved_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photos available in this channel!.
        /// </summary>
        public static string Channels_NoPhotos {
            get {
                return ResourceManager.GetString("Channels_NoPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Channels_Refresh {
            get {
                return ResourceManager.GetString("Channels_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will reset wallpaper sequence in non-random mode.
        /// </summary>
        public static string Channels_RefreshTooltip {
            get {
                return ResourceManager.GetString("Channels_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ContextMenu_Download {
            get {
                return ResourceManager.GetString("ContextMenu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Author.
        /// </summary>
        public static string ContextMenu_HideAuthor {
            get {
                return ResourceManager.GetString("ContextMenu_HideAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Wallpaper.
        /// </summary>
        public static string ContextMenu_HideWallpaper {
            get {
                return ResourceManager.GetString("ContextMenu_HideWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Wallpaper.
        /// </summary>
        public static string ContextMenu_SetWallpaper {
            get {
                return ResourceManager.GetString("ContextMenu_SetWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View User Profile.
        /// </summary>
        public static string ContextMenu_ViewAuthor {
            get {
                return ResourceManager.GetString("ContextMenu_ViewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on Unsplash.
        /// </summary>
        public static string ContextMenu_ViewPhoto {
            get {
                return ResourceManager.GetString("ContextMenu_ViewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Day.
        /// </summary>
        public static string Interval_Day {
            get {
                return ResourceManager.GetString("Interval_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hour.
        /// </summary>
        public static string Interval_Hour {
            get {
                return ResourceManager.GetString("Interval_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hours.
        /// </summary>
        public static string Interval_Hours {
            get {
                return ResourceManager.GetString("Interval_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Interval_Manual {
            get {
                return ResourceManager.GetString("Interval_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minutes.
        /// </summary>
        public static string Interval_Minutes {
            get {
                return ResourceManager.GetString("Interval_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Msg_Hint {
            get {
                return ResourceManager.GetString("Msg_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Irvue like application for Windows....
        /// </summary>
        public static string Settings_AboutContent {
            get {
                return ResourceManager.GetString("Settings_AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Settings_Browse {
            get {
                return ResourceManager.GetString("Settings_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string Settings_Choose_Folder {
            get {
                return ResourceManager.GetString("Settings_Choose_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear App Cache.
        /// </summary>
        public static string Settings_ClearCache {
            get {
                return ResourceManager.GetString("Settings_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete all wallpaper cache?.
        /// </summary>
        public static string Settings_ClearCache_Confirm {
            get {
                return ResourceManager.GetString("Settings_ClearCache_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Wallpaper.
        /// </summary>
        public static string Settings_DiffWallpaper {
            get {
                return ResourceManager.GetString("Settings_DiffWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Display Mode:.
        /// </summary>
        public static string Settings_DisplayMode {
            get {
                return ResourceManager.GetString("Settings_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Settings_Enable {
            get {
                return ResourceManager.GetString("Settings_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Portraits and Full Body.
        /// </summary>
        public static string Settings_Filter_AllPeople {
            get {
                return ResourceManager.GetString("Settings_Filter_AllPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Settings_Filter_None {
            get {
                return ResourceManager.GetString("Settings_Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Portraits.
        /// </summary>
        public static string Settings_Filter_Portraits {
            get {
                return ResourceManager.GetString("Settings_Filter_Portraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot select system/hidden folder!.
        /// </summary>
        public static string Settings_Folder_Error {
            get {
                return ResourceManager.GetString("Settings_Folder_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Settings_Language_Auto {
            get {
                return ResourceManager.GetString("Settings_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese-Simplified.
        /// </summary>
        public static string Settings_Language_Chinese {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch at Startup:.
        /// </summary>
        public static string Settings_LaunchAtStartup {
            get {
                return ResourceManager.GetString("Settings_LaunchAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Resolution:.
        /// </summary>
        public static string Settings_MinResolution {
            get {
                return ResourceManager.GetString("Settings_MinResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Settings_Mode_Center {
            get {
                return ResourceManager.GetString("Settings_Mode_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string Settings_Mode_Fill {
            get {
                return ResourceManager.GetString("Settings_Mode_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        public static string Settings_Mode_Fit {
            get {
                return ResourceManager.GetString("Settings_Mode_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Resolution.
        /// </summary>
        public static string Settings_MonitorResolution {
            get {
                return ResourceManager.GetString("Settings_MonitorResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Monitor:.
        /// </summary>
        public static string Settings_MultiMonitor {
            get {
                return ResourceManager.GetString("Settings_MultiMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Saved Wallpapers:.
        /// </summary>
        public static string Settings_OpenSaved {
            get {
                return ResourceManager.GetString("Settings_OpenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape and Portrait.
        /// </summary>
        public static string Settings_Ratio_Both {
            get {
                return ResourceManager.GetString("Settings_Ratio_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string Settings_Ratio_Landscape {
            get {
                return ResourceManager.GetString("Settings_Ratio_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string Settings_Ratio_Portrait {
            get {
                return ResourceManager.GetString("Settings_Ratio_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Ratio Preference:.
        /// </summary>
        public static string Settings_RatioPref {
            get {
                return ResourceManager.GetString("Settings_RatioPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset App.
        /// </summary>
        public static string Settings_ResetApp {
            get {
                return ResourceManager.GetString("Settings_ResetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the app? This will delete all data and restart the application..
        /// </summary>
        public static string Settings_ResetApp_Confirm {
            get {
                return ResourceManager.GetString("Settings_ResetApp_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Wallpaper.
        /// </summary>
        public static string Settings_SameWallpaper {
            get {
                return ResourceManager.GetString("Settings_SameWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Save Path:.
        /// </summary>
        public static string Settings_SavePath {
            get {
                return ResourceManager.GetString("Settings_SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Filter:.
        /// </summary>
        public static string Settings_SmartFilter {
            get {
                return ResourceManager.GetString("Settings_SmartFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_Tab_About {
            get {
                return ResourceManager.GetString("Settings_Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Settings_Tab_Filter {
            get {
                return ResourceManager.GetString("Settings_Tab_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_Tab_General {
            get {
                return ResourceManager.GetString("Settings_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Settings_Theme_Auto {
            get {
                return ResourceManager.GetString("Settings_Theme_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Wallpaper.
        /// </summary>
        public static string Tray_AboutWallpaper {
            get {
                return ResourceManager.GetString("Tray_AboutWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Channel.
        /// </summary>
        public static string Tray_AddChannel {
            get {
                return ResourceManager.GetString("Tray_AddChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change All Wallpaper.
        /// </summary>
        public static string Tray_ChangeAllWallpaper {
            get {
                return ResourceManager.GetString("Tray_ChangeAllWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Wallpaper.
        /// </summary>
        public static string Tray_ChangeWallpaper {
            get {
                return ResourceManager.GetString("Tray_ChangeWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Tray_Channels {
            get {
                return ResourceManager.GetString("Tray_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Wallpaper.
        /// </summary>
        public static string Tray_DownloadWallpaper {
            get {
                return ResourceManager.GetString("Tray_DownloadWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is OK!.
        /// </summary>
        public static string Tray_Everything_Is_OK {
            get {
                return ResourceManager.GetString("Tray_Everything_Is_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Channel.
        /// </summary>
        public static string Tray_ManageChannel {
            get {
                return ResourceManager.GetString("Tray_ManageChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Update: .
        /// </summary>
        public static string Tray_Next_Update {
            get {
                return ResourceManager.GetString("Tray_Next_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Wallpaper.
        /// </summary>
        public static string Tray_PreviousWallpaper {
            get {
                return ResourceManager.GetString("Tray_PreviousWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Wallpaper.
        /// </summary>
        public static string Tray_RandomWallpaper {
            get {
                return ResourceManager.GetString("Tray_RandomWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        public static string Tray_UpdateInterval {
            get {
                return ResourceManager.GetString("Tray_UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Uni_Cancel {
            get {
                return ResourceManager.GetString("Uni_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Details.
        /// </summary>
        public static string Wallpaper_Details {
            get {
                return ResourceManager.GetString("Wallpaper_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Downloads.
        /// </summary>
        public static string Wallpaper_Downloads {
            get {
                return ResourceManager.GetString("Wallpaper_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Likes.
        /// </summary>
        public static string Wallpaper_Likes {
            get {
                return ResourceManager.GetString("Wallpaper_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo by {0}.
        /// </summary>
        public static string Wallpaper_PhotoBy {
            get {
                return ResourceManager.GetString("Wallpaper_PhotoBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Window_Channels_Title {
            get {
                return ResourceManager.GetString("Window_Channels_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Window_Settings_Title {
            get {
                return ResourceManager.GetString("Window_Settings_Title", resourceCulture);
            }
        }
    }
}
