//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irvuewin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Irvuewin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AddChannel 的本地化字符串。
        /// </summary>
        public static string Add_Channel {
            get {
                return ResourceManager.GetString("Add_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add_Channel_Confirm {
            get {
                return ResourceManager.GetString("Add_Channel_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type keyword or Unsplash channel URL to search 的本地化字符串。
        /// </summary>
        public static string Add_Channel_Input_Placeholder {
            get {
                return ResourceManager.GetString("Add_Channel_Input_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsplash URLs below are supported: 的本地化字符串。
        /// </summary>
        public static string Add_Channel_Instruction {
            get {
                return ResourceManager.GetString("Add_Channel_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select at least 1 channel 的本地化字符串。
        /// </summary>
        public static string Add_Channel_NoneSelect_Msg {
            get {
                return ResourceManager.GetString("Add_Channel_NoneSelect_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explore Unsplash to find more channels: 的本地化字符串。
        /// </summary>
        public static string Add_Channel_Result_Placeholder {
            get {
                return ResourceManager.GetString("Add_Channel_Result_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Unsplash.com 的本地化字符串。
        /// </summary>
        public static string Add_Channel_Unsplash_Link {
            get {
                return ResourceManager.GetString("Add_Channel_Unsplash_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not delete reserved channel 的本地化字符串。
        /// </summary>
        public static string Channel_Reserved_Channel {
            get {
                return ResourceManager.GetString("Channel_Reserved_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No photos available in this channel! 的本地化字符串。
        /// </summary>
        public static string Channels_NoPhotos {
            get {
                return ResourceManager.GetString("Channels_NoPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Channels_Refresh {
            get {
                return ResourceManager.GetString("Channels_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will reset wallpaper sequence in non-random mode 的本地化字符串。
        /// </summary>
        public static string Channels_RefreshTooltip {
            get {
                return ResourceManager.GetString("Channels_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Day 的本地化字符串。
        /// </summary>
        public static string Interval_Day {
            get {
                return ResourceManager.GetString("Interval_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Hour 的本地化字符串。
        /// </summary>
        public static string Interval_Hour {
            get {
                return ResourceManager.GetString("Interval_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Hours 的本地化字符串。
        /// </summary>
        public static string Interval_Hours {
            get {
                return ResourceManager.GetString("Interval_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        public static string Interval_Manual {
            get {
                return ResourceManager.GetString("Interval_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Minutes 的本地化字符串。
        /// </summary>
        public static string Interval_Minutes {
            get {
                return ResourceManager.GetString("Interval_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Msg_Hint {
            get {
                return ResourceManager.GetString("Msg_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Irvue like application for Windows... 的本地化字符串。
        /// </summary>
        public static string Settings_AboutContent {
            get {
                return ResourceManager.GetString("Settings_AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        public static string Settings_Browse {
            get {
                return ResourceManager.GetString("Settings_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder 的本地化字符串。
        /// </summary>
        public static string Settings_Choose_Folder {
            get {
                return ResourceManager.GetString("Settings_Choose_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear App Cache 的本地化字符串。
        /// </summary>
        public static string Settings_ClearCache {
            get {
                return ResourceManager.GetString("Settings_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm to delete all wallpaper cache? 的本地化字符串。
        /// </summary>
        public static string Settings_ClearCache_Confirm {
            get {
                return ResourceManager.GetString("Settings_ClearCache_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Different Wallpaper 的本地化字符串。
        /// </summary>
        public static string Settings_DiffWallpaper {
            get {
                return ResourceManager.GetString("Settings_DiffWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper Display Mode: 的本地化字符串。
        /// </summary>
        public static string Settings_DisplayMode {
            get {
                return ResourceManager.GetString("Settings_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Settings_Enable {
            get {
                return ResourceManager.GetString("Settings_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Portraits and Full Body 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_AllPeople {
            get {
                return ResourceManager.GetString("Settings_Filter_AllPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_None {
            get {
                return ResourceManager.GetString("Settings_Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Portraits 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Portraits {
            get {
                return ResourceManager.GetString("Settings_Filter_Portraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot select system/hidden folder! 的本地化字符串。
        /// </summary>
        public static string Settings_Folder_Error {
            get {
                return ResourceManager.GetString("Settings_Folder_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Auto {
            get {
                return ResourceManager.GetString("Settings_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese-Simplified 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Chinese {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch at Startup: 的本地化字符串。
        /// </summary>
        public static string Settings_LaunchAtStartup {
            get {
                return ResourceManager.GetString("Settings_LaunchAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Resolution: 的本地化字符串。
        /// </summary>
        public static string Settings_MinResolution {
            get {
                return ResourceManager.GetString("Settings_MinResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string Settings_Mode_Center {
            get {
                return ResourceManager.GetString("Settings_Mode_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill 的本地化字符串。
        /// </summary>
        public static string Settings_Mode_Fill {
            get {
                return ResourceManager.GetString("Settings_Mode_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit 的本地化字符串。
        /// </summary>
        public static string Settings_Mode_Fit {
            get {
                return ResourceManager.GetString("Settings_Mode_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor Resolution 的本地化字符串。
        /// </summary>
        public static string Settings_MonitorResolution {
            get {
                return ResourceManager.GetString("Settings_MonitorResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi-Monitor: 的本地化字符串。
        /// </summary>
        public static string Settings_MultiMonitor {
            get {
                return ResourceManager.GetString("Settings_MultiMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Saved Wallpapers: 的本地化字符串。
        /// </summary>
        public static string Settings_OpenSaved {
            get {
                return ResourceManager.GetString("Settings_OpenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landscape and Portrait 的本地化字符串。
        /// </summary>
        public static string Settings_Ratio_Both {
            get {
                return ResourceManager.GetString("Settings_Ratio_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landscape 的本地化字符串。
        /// </summary>
        public static string Settings_Ratio_Landscape {
            get {
                return ResourceManager.GetString("Settings_Ratio_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portrait 的本地化字符串。
        /// </summary>
        public static string Settings_Ratio_Portrait {
            get {
                return ResourceManager.GetString("Settings_Ratio_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper Ratio Preference: 的本地化字符串。
        /// </summary>
        public static string Settings_RatioPref {
            get {
                return ResourceManager.GetString("Settings_RatioPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset App 的本地化字符串。
        /// </summary>
        public static string Settings_ResetApp {
            get {
                return ResourceManager.GetString("Settings_ResetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to reset the app? This will delete all data and restart the application. 的本地化字符串。
        /// </summary>
        public static string Settings_ResetApp_Confirm {
            get {
                return ResourceManager.GetString("Settings_ResetApp_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same Wallpaper 的本地化字符串。
        /// </summary>
        public static string Settings_SameWallpaper {
            get {
                return ResourceManager.GetString("Settings_SameWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper Save Path: 的本地化字符串。
        /// </summary>
        public static string Settings_SavePath {
            get {
                return ResourceManager.GetString("Settings_SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smart Filter: 的本地化字符串。
        /// </summary>
        public static string Settings_SmartFilter {
            get {
                return ResourceManager.GetString("Settings_SmartFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Settings_Tab_About {
            get {
                return ResourceManager.GetString("Settings_Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string Settings_Tab_Filter {
            get {
                return ResourceManager.GetString("Settings_Tab_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string Settings_Tab_General {
            get {
                return ResourceManager.GetString("Settings_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme: 的本地化字符串。
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Auto {
            get {
                return ResourceManager.GetString("Settings_Theme_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Wallpaper 的本地化字符串。
        /// </summary>
        public static string Tray_AboutWallpaper {
            get {
                return ResourceManager.GetString("Tray_AboutWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 + Add Channel 的本地化字符串。
        /// </summary>
        public static string Tray_AddChannel {
            get {
                return ResourceManager.GetString("Tray_AddChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change All Wallpaper 的本地化字符串。
        /// </summary>
        public static string Tray_ChangeAllWallpaper {
            get {
                return ResourceManager.GetString("Tray_ChangeAllWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Wallpaper 的本地化字符串。
        /// </summary>
        public static string Tray_ChangeWallpaper {
            get {
                return ResourceManager.GetString("Tray_ChangeWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channels 的本地化字符串。
        /// </summary>
        public static string Tray_Channels {
            get {
                return ResourceManager.GetString("Tray_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Wallpaper 的本地化字符串。
        /// </summary>
        public static string Tray_DownloadWallpaper {
            get {
                return ResourceManager.GetString("Tray_DownloadWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything is OK! 的本地化字符串。
        /// </summary>
        public static string Tray_Everything_Is_OK {
            get {
                return ResourceManager.GetString("Tray_Everything_Is_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Channel 的本地化字符串。
        /// </summary>
        public static string Tray_ManageChannel {
            get {
                return ResourceManager.GetString("Tray_ManageChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Update:  的本地化字符串。
        /// </summary>
        public static string Tray_Next_Update {
            get {
                return ResourceManager.GetString("Tray_Next_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Wallpaper 的本地化字符串。
        /// </summary>
        public static string Tray_PreviousWallpaper {
            get {
                return ResourceManager.GetString("Tray_PreviousWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Wallpaper 的本地化字符串。
        /// </summary>
        public static string Tray_RandomWallpaper {
            get {
                return ResourceManager.GetString("Tray_RandomWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Interval 的本地化字符串。
        /// </summary>
        public static string Tray_UpdateInterval {
            get {
                return ResourceManager.GetString("Tray_UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Uni_Cancel {
            get {
                return ResourceManager.GetString("Uni_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper Details 的本地化字符串。
        /// </summary>
        public static string Wallpaper_Details {
            get {
                return ResourceManager.GetString("Wallpaper_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Downloads 的本地化字符串。
        /// </summary>
        public static string Wallpaper_Downloads {
            get {
                return ResourceManager.GetString("Wallpaper_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Likes 的本地化字符串。
        /// </summary>
        public static string Wallpaper_Likes {
            get {
                return ResourceManager.GetString("Wallpaper_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo by {0} 的本地化字符串。
        /// </summary>
        public static string Wallpaper_PhotoBy {
            get {
                return ResourceManager.GetString("Wallpaper_PhotoBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channels 的本地化字符串。
        /// </summary>
        public static string Window_Channels_Title {
            get {
                return ResourceManager.GetString("Window_Channels_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Window_Settings_Title {
            get {
                return ResourceManager.GetString("Window_Settings_Title", resourceCulture);
            }
        }
    }
}
