//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irvuewin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte MultiDisplay {
            get {
                return ((byte)(this["MultiDisplay"]));
            }
            set {
                this["MultiDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte WallpaperMode {
            get {
                return ((byte)(this["WallpaperMode"]));
            }
            set {
                this["WallpaperMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenSavedWallpaper {
            get {
                return ((bool)(this["OpenSavedWallpaper"]));
            }
            set {
                this["OpenSavedWallpaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WallpaperSavedPath {
            get {
                return ((string)(this["WallpaperSavedPath"]));
            }
            set {
                this["WallpaperSavedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LaunchAtLogin {
            get {
                return ((bool)(this["LaunchAtLogin"]));
            }
            set {
                this["LaunchAtLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte WallpaperOrientation {
            get {
                return ((byte)(this["WallpaperOrientation"]));
            }
            set {
                this["WallpaperOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte SmartFilter {
            get {
                return ((byte)(this["SmartFilter"]));
            }
            set {
                this["SmartFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public float MinResolution {
            get {
                return ((float)(this["MinResolution"]));
            }
            set {
                this["MinResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort WallpaperChangeInterval {
            get {
                return ((ushort)(this["WallpaperChangeInterval"]));
            }
            set {
                this["WallpaperChangeInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RandomWallpaper {
            get {
                return ((bool)(this["RandomWallpaper"]));
            }
            set {
                this["RandomWallpaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public sbyte SelectedChannelIndex {
            get {
                return ((sbyte)(this["SelectedChannelIndex"]));
            }
            set {
                this["SelectedChannelIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client-ID gOjCXnSXiHRasWqeABszxQQCsBJgceXSjHdZYVTfZR8")]
        public string DefaultUnsplashApiKey {
            get {
                return ((string)(this["DefaultUnsplashApiKey"]));
            }
            set {
                this["DefaultUnsplashApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserUnsplashApiKey {
            get {
                return ((string)(this["UserUnsplashApiKey"]));
            }
            set {
                this["UserUnsplashApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("317099,7282015,raoebyzOILQ,62652795")]
        public string UserUnsplashChannels {
            get {
                return ((string)(this["UserUnsplashChannels"]));
            }
            set {
                this["UserUnsplashChannels"] = value;
            }
        }
    }
}
